- type: job
  id: MPMedic
  name: job-name-mpmedic
  description: job-description-mpmedic
  playTimeTracker: JobMPMedic
  setPreference: true
  startingGear: MPMedicGear
  icon: "JobIconMPMedic"
  supervisors: job-supervisors-sc
  requirements:
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 80
  accessGroups:
  - Command
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: MPMedicGear
  equipment:
    id: MilitaryPoliceMedicPDA
    head: ClothingHeadHatBeretMilitaryPoliceMedic
    eyes: ClothingEyesGlassesMilitaryPoliceMedic
    ears: ClothingHeadsetMilitaryPoliceMedic
    mask: ClothingMaskSterile
    neck: SecurityWhistle
    outerClothing: ClothingOuterArmorBasic
    jumpsuit: ClothingUniformJumpsuitMilitaryPoliceOfficer
    gloves: ClothingHandsGlovesNitrile
    back: ClothingBackpackMilitaryPolice
    belt: ClothingBeltMilitaryPoliceMedicFilled
    shoes: ClothingShoesBootsCombatFilled
