- type: job
  id: MPChief
  name: job-name-mpchief
  description: job-description-mpchief
  playTimeTracker: JobMPChief
  setPreference: true
  startingGear: MPChiefGear
  icon: "JobIconMPChief"
  supervisors: job-supervisors-to
  requirements:
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 100
  accessGroups:
  - Command

- type: startingGear
  id: MPChiefGear
  equipment:
    shoes: ClothingShoesBootsJack
    id: HoSPDA
    ears: ClothingHeadsetCommandingOfficer
    belt: ClothingBeltSecurity
    uniform: ClothingUniformJumpsuitHoS
