- type: job
  id: MPOfficer
  name: job-name-mpofficer
  description: job-description-mpofficer
  playTimeTracker: JobMPOfficer
  setPreference: true
  startingGear: MPOfficerGear
  icon: "JobIconMPOfficer"
  supervisors: job-supervisors-sc
  requirements:
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 60
  accessGroups:
  - Command

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: MPOfficerGear
  equipment:
    id: SecurityPDA
    head: ClothingHeadHatBeretSecurity
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    mask: ClothingMaskNeckGaiter
    neck: SecurityWhistle
    outerClothing: ClothingOuterArmorBasic
    jumpsuit: ClothingUniformJumpsuitMilitaryPoliceOfficer
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackSecurity
    belt: ClothingBeltSecurityWebbingFilled
    shoes: ClothingShoesBootsCombatFilled
