- type: job
  id: SecurityTrainee
  name: job-name-security-trainee
  description: job-description-security-trainee
  playTimeTracker: JobSecurityTrainee
  setPreference: true
  startingGear: SecurityTraineeGear
  icon: "JobIconSecurityTrainee"
  supervisors: job-supervisors-sc
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
  displayWeight: 40
  canBeAntag: false
  accessGroups:
  - Command

- type: startingGear
  id: SecurityTraineeGear
  equipment:
    shoes: ClothingShoesBootsJack
    id: HoSPDA
    ears: ClothingHeadsetCommandingOfficer
    belt: ClothingBeltSecurity
    uniform: ClothingUniformJumpsuitSec
