using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.FlagShip.Client.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragment : BoxContainer
{
}
