- type: job
  id: BridgeEnsign
  name: job-name-bridgeensign
  description: job-description-bridgeensign
  playTimeTracker: JobBridgeEnsign
  setPreference: true
  supervisors: job-supervisors-bs
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours

  displayWeight: 40
  startingGear: BridgeEnsignGear
  icon: "JobIconBridgeEnsign"
  access:
  - Captain
  accessGroups:
  - Command
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: BridgeEnsignGear
  equipment:
    id: BridgeEnsignPDA
    head: ClothingHeadHatBridgeEnsignSoft
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetAltBridgeEnsign
    jumpsuit: ClothingUniformJumpsuitBridgeCommand
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackSatchelBridgeCommand
    shoes: ClothingShoesBootsJack
  storage:
    back:
    - Flash
