- type: job
  id: BridgeEnsign
  name: job-name-bridgeensign
  description: job-description-bridgeensign
  playTimeTracker: JobBridgeEnsign
  setPreference: true
  setRankPreference: true
  supervisors: job-supervisors-bs
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours

  displayWeight: 40
  startingGear: BridgeEnsignGear
  icon: "JobIconBridgeEnsign"
  access:
  - Captain
  accessGroups:
  - Command
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

- type: startingGear
  id: BridgeEnsignGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBridgeCommand
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatBridgeEnsignSoft
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackSatchelBridgeCommand
    id: BridgeEnsignPDA
    ears: ClothingHeadsetAltBridgeEnsign
  storage:
    back:
    - Flash
