- type: job
  id: CommandingOfficer
  name: job-name-commandingofficer
  description: job-description-commandingofficer
  playTimeTracker: JobCommandingOfficer
  setPreference: true
  supervisors: job-supervisors-hc
  requireAdminNotify: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
  displayWeight: 100
  startingGear: CommandingOfficerGear
  icon: "JobIconCommandingOfficer"
  joinNotifyCrew: true
  accessGroups:
  - Command
  - AllAccess
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

- type: startingGear
  id: CommandingOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommandingOfficer
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCommandingOfficer
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackSatchelBridgeCommand
    id: CommandingOfficerPDA
    ears: ClothingHeadsetAltCommandingOfficer
