- type: job
  id: ExecutiveOfficer
  name: job-name-executiveofficer
  description: job-description-executiveofficer
  playTimeTracker: JobExecutiveOfficer
  setPreference: true
  supervisors: job-supervisors-co
  requireAdminNotify: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 90
  startingGear: ExecutiveOfficerGear
  icon: "JobIconExecutiveOfficer"
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: ExecutiveOfficerGear
  equipment:
    id: ExecutiveOfficerPDA
    head: ClothingHeadHatBeretNavy
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetAltExecutiveOfficer
    jumpsuit: ClothingUniformJumpsuitExecutiveOfficer
    gloves: ClothingHandsGlovesNavyOfficer
    back: ClothingBackpackSatchelBridgeCommand
    shoes: ClothingShoesBootsJack
  storage:
    back:
    - Flash
