- type: job
  id: FlightControlOfficer
  name: job-name-flightcontrolofficer
  description: job-description-flightcontrolofficer
  playTimeTracker: JobFlightControlOfficer
  setPreference: true
  supervisors: job-supervisors-coxo
  requireAdminNotify: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 50
  startingGear: FlightControlOfficerGear
  icon: "JobIconFlightControlOfficer"
  access:
  - Captain
  accessGroups:
  - Command
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: FlightControlOfficerGear
  equipment:
    id: FlightControlOfficerPDA
    head: ClothingHeadHatBeretNavy
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetAltFlightControlOfficer
    jumpsuit: ClothingUniformJumpsuitBridgeCommand
    gloves: ClothingHandsGlovesNavyOfficer
    back: ClothingBackpackSatchelBridgeCommand
    shoes: ClothingShoesBootsJack
  storage:
    back:
    - Flash
