- type: job
  id: FlightControlOfficer
  name: job-name-flightcontrolofficer
  description: job-description-flightcontrolofficer
  playTimeTracker: JobFlightControlOfficer
  setPreference: true
  setRankPreference: true
  supervisors: job-supervisors-coxo
  requireAdminNotify: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 50
  startingGear: FlightControlOfficerGear
  icon: "JobIconFlightControlOfficer"
  access:
  - Captain
  accessGroups:
  - Command
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

- type: startingGear
  id: FlightControlOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBridgeCommand
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatBeretNavy
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesNavyOfficer
    back: ClothingBackpackSatchelBridgeCommand
    id: FlightControlOfficerPDA
    ears: ClothingHeadsetAltFlightControlOfficer
  storage:
    back:
    - Flash
