- type: job
  id: TacticalOfficer
  name: job-name-tacticalofficer
  description: job-description-tacticalofficer
  playTimeTracker: JobTacticalOfficer
  setPreference: true # Frontier
  supervisors: job-supervisors-coxo
  requireAdminNotify: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 54000 # 15 hours
  displayWeight: 80
  startingGear: TacticalOfficerGear
  icon: "JobIconTacticalOfficer"
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess
  special:
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
     components:
       - type: CommandStaff

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: TacticalOfficerGear
  equipment:
    id: TacticalOfficerPDA
    head: ClothingHeadHatBeretNavy
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetAltTacticalOfficer
    jumpsuit: ClothingUniformJumpsuitTacticalOfficer
    gloves: ClothingHandsGlovesNavyOfficer
    back: ClothingBackpackSatchelBridgeCommand
    shoes: ClothingShoesBootsJack
  storage:
    back:
    - Flash
