- type: job
  id: ChiefOfMaintenance
  name: job-name-chiefofmaintenance
  description: job-description-chiefofmaintenance
  playTimeTracker: JobChiefOfMaintenance
  setPreference: true
  requireAdminNotify: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  displayWeight: 100
  startingGear: ChiefOfMaintenanceGear
  icon: "JobIconChiefOfMaintenance"
  supervisors: job-supervisors-to
  accessGroups:
  - Command

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: ChiefOfMaintenanceGear
  equipment:
    id: CEPDA
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    outerClothing: ClothingOuterVestHazard
    jumpsuit: ClothingUniformJumpsuitMaintenanceTechnician
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackEngineering
    belt: ClothingBeltUtilityEngineering
    shoes: ClothingShoesBootsWork
  storage:
    back:
    - Flash
