- type: job
  id: LifeSupportSpecialist
  name: job-name-lifesupportspecialist
  description: job-description-lifesupportspecialist
  playTimeTracker: JobLifeSupportSpecialist
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  displayWeight: 90
  startingGear: LifeSupportSpecialistGear
  icon: "JobIconLifeSupportSpecialist"
  supervisors: job-supervisors-com
  accessGroups:
  - Command
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: LifeSupportSpecialistGear
  equipment:
    id: AtmosPDA
    head: ClothingHeadHatHardhatOrange
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetEngineering
    outerClothing: ClothingOuterVestHazard
    jumpsuit: ClothingUniformJumpsuitMaintenanceTechnician
    gloves: ClothingHandsGlovesColorOrange
    back: ClothingBackpackAtmospherics
    belt: ClothingBeltUtilityEngineering
    shoes: ClothingShoesBootsWork
