- type: job
  id: MaintenanceIntern
  name: job-name-maintenanceintern
  description: job-description-maintenanceintern
  playTimeTracker: JobMaintenanceIntern
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Engineering
#      time: 54000 #15 hrs
#      inverted: true # stop playing intern if you're good at engineering!
    - !type:OverallPlaytimeRequirement
      time: 10800 #
  displayWeight: 70
  startingGear: MaintenanceInternGear
  icon: "JobIconMaintenanceIntern"
  supervisors: job-supervisors-com
  accessGroups:
  - Command
  setPreference: true

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: MaintenanceInternGear
  equipment:
    id: TechnicalAssistantPDA
    head: ClothingHeadHatOrangesoft
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetEngineering
    outerClothing: ClothingOuterVestHazard
    jumpsuit: ClothingUniformJumpsuitMaintenanceTechnician
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackEngineering
    belt: ClothingBeltUtilityEngineering
    shoes: ClothingShoesBootsWork
