- type: department
  id: BridgeCommand
  name: department-BridgeCommand
  description: department-BridgeCommand-description
  color: "#2b72ee"
  weight: 200
  primary: false
  roles:
  - CommandingOfficer
  - ExecutiveOfficer
  - TacticalOfficer
  - OperationsOfficer
  - CommunicationsOfficer
  - FlightControlOfficer
  - BridgeEnsign

- type: department
  id: MilitaryPolice
  name: department-MilitaryPolice
  description: department-MilitaryPolice-description
  color: "#2b72ee"
  weight: 180
  primary: false
  roles:
  - MPChief
  - MPMedic
  - MPOfficer
  - MPTrainee

- type: department
  id: Supply
  name: department-Supply
  description: department-Supply-description
  color: "#6aa84f"
  weight: 160
  primary: false
  roles:
  - SuppliesQuartermaster
  - ArtillerySpecialist
  - SuppliesCrewman

- type: department
  id: Maintenance
  name: department-Maintenance
  description: department-Maintenance-description
  color: "#EFB341"
  weight: 140
  primary: false
  roles:
  - ChiefOfMaintenance
  - MaintenanceTechnician
  - LifeSupportSpecialist
  - MaintenanceIntern

- type: department
  id: FlagScience
  name: department-FlagScience
  description: department-FlagScience-description
  color: "#cd7ccd"
  weight: 120
  primary: false
  roles:
  - ScienceSupervisor
  - FlagRoboticist
  - FlagScientist
  - FlagResearchAssistant

- type: department
  id: FlagMedical
  name: department-FlagMedical
  description: department-FlagMedical-description
  color: "#a4d8ef"
  weight: 100
  primary: false
  roles:
  - ChiefOfMedical
  - FlagMedicalDoctor
  - FlagChemist
  - ParamedicalSpecialist
  - FlagMedicalIntern

- type: department
  id: Service
  name: department-Service
  description: department-Service-description
  color: "#c1ff72"
  weight: 0
  primary: true
  roles:
  - FlagBartender
  - HydroponicsBiologist
  - MessChef
  - Custodian
  - OffDutyCrew
