using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.FlagShip.Client.Market.UI;

[GenerateTypedNameReferences]
public sealed partial class MarketCartProductRow : PanelContainer
{
    public EntityPrototype Prototype;
    public MarketCartProductRow(EntityPrototype prototype)
    {
        RobustXamlLoader.Load(this);
        Prototype = prototype;
    }
}
