using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.FlagShip.Client.Pirate.UI;

[GenerateTypedNameReferences]
public sealed partial class PirateBountyRedemptionMenu : FancyWindow
{
    public Action? SellRequested;

    public PirateBountyRedemptionMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }
}
