- type: job
  id: SecurityOfficerOld
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficerOld
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
  startingGear: SecurityOfficerOldGear
  icon: "JobIconSecurityOfficerOld"
  supervisors: job-supervisors-hos
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerOldGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
