using Content.Client.Guidebook;
using Content.FlagShip.Shared.Shipyard.Prototypes;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.FlagShip.Client.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class VesselRow : PanelContainer
{
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    private readonly GuidebookSystem _guidebook = default!;
    public VesselPrototype? Vessel;
    public VesselRow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _guidebook = _entitySystem.GetEntitySystem<GuidebookSystem>();

        Content.FlagShip.Client.Guidebook.OnPressed += LoadVesselGuidebook;
    }

    private void LoadVesselGuidebook(BaseButton.ButtonEventArgs args)
    {
        if (Vessel?.GuidebookPage == null)
            return;

        List<ProtoId<GuideEntryPrototype>> guidebookEntries = new() { Vessel.GuidebookPage.Value };
        _guidebook.OpenHelp(guidebookEntries);
    }
}
