- type: job
  id: FlagChemist
  name: job-name-flag-chemist
  description: job-description-flag-chemist
  playTimeTracker: JobFlagChemist
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagMedical
      time: 36000 #10 hrs
  displayWeight: 60
  startingGear: FlagChemistGear
  icon: "JobIconFlagChemist"
  supervisors: job-supervisors-chom
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: FlagChemistGear
  equipment:
    id: ChemistryPDA
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesGlassesChemical
    ears: ClothingHeadsetMedical
    mask: ClothingMaskSterile
    jumpsuit: ClothingUniformJumpsuitFlagMedicalDoctor
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsGlovesNitrile
    back: ClothingBackpackChemistry
    belt: ClothingBeltMedical
    shoes: ClothingShoesColorWhite
