- type: job
  id: ChiefOfMedical
  name: job-name-chiefofmedical
  description: job-description-chiefofmedical
  playTimeTracker: JobChiefOfMedical
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagMedical
      time: 54000 #15 hrs
  displayWeight: 100
  startingGear: ChiefOfMedicalGear
  icon: "JobIconChiefOfMedical"
  supervisors: job-supervisors-oo
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: ChiefOfMedicalGear
  equipment:
    id: CMOPDA
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetCMO
    mask: ClothingMaskSterile
    jumpsuit: ClothingUniformJumpsuitFlagMedicalDoctor
    outerClothing: ClothingOuterCoatLabCmoOpened
    gloves: ClothingHandsGlovesNitrile
    back: ClothingBackpackMedical
    belt: ClothingBeltMedical
    shoes: ClothingShoesColorWhite
  storage:
    back:
    - Flash
