- type: job
  id: FlagMedicalIntern
  name: job-name-flag-medicalintern
  description: job-description-flag-medicalintern
  playTimeTracker: JobFlagMedicalIntern
  setPreference: true
  displayWeight: 20
  startingGear: FlagMedicalInternGear
  icon: "JobIconFlagMedicalIntern"
  supervisors: job-supervisors-chom
  access:
  - Medical
  - Maintenance

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: FlagMedicalInternGear
  equipment:
    id: MedicalInternPDA
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetMedical
    mask: ClothingMaskSterile
    jumpsuit: ClothingUniformJumpsuitFlagMedicalDoctor
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsGlovesNitrile
    back: ClothingBackpackMedical
    belt: ClothingBeltMedical
    shoes: ClothingShoesColorWhite
