- type: job
  id: FlagMedicalDoctor
  name: job-name-flag-medicaldoctor
  description: job-description-flag-medicaldoctor
  playTimeTracker: JobFlagMedicalDoctor
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagMedical
      time: 36000 #10 hrs
  displayWeight: 80
  startingGear: FlagMedicalDoctorGear
  icon: "JobIconFlagMedicalDoctor"
  supervisors: job-supervisors-chom
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: FlagMedicalDoctorGear
  equipment:
    id: MedicalPDA
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetMedical
    mask: ClothingMaskSterile
    jumpsuit: ClothingUniformJumpsuitFlagMedicalDoctor
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsGlovesNitrile
    back: ClothingBackpackMedical
    belt: ClothingBeltMedical
    shoes: ClothingShoesColorWhite
