- type: job
  id: ParamedicalSpecialist
  name: job-name-paramedicalspecialist
  description: job-description-paramedicalspecialist
  playTimeTracker: JobParamedicalSpecialist
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagMedical
      time: 18000 #5 hrs
  displayWeight: 40
  startingGear: ParamedicalSpecialistGear
  icon: "JobIconParamedicalSpecialist"
  supervisors: job-supervisors-chom
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: ParamedicalSpecialistGear
  equipment:
    id: ParamedicPDA
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetMedical
    mask: ClothingMaskSterile
    jumpsuit: ClothingUniformJumpsuitFlagMedicalDoctor
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesNitrile
    back: ClothingBackpackMedical
    belt: ClothingBeltMedicalEMT
    shoes: ClothingShoesColorWhite
