- type: job
  id: ArtillerySpecialist
  name: job-name-artilleryspecialist
  description: job-description-artilleryspecialist
  playTimeTracker: JobArtillerySpecialist
  setPreference: true
  supervisors: job-supervisors-sq
  requirements:
    - !type:DepartmentTimeRequirement
      department: Supply
      time: 36000 # 10 hours
  displayWeight: 80
  startingGear: ArtillerySpecialistGear
  icon: "JobIconArtillerySpecialist"
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: ArtillerySpecialistGear
  equipment:
    id: CargoPDA
    head: ClothingHeadHatBeretArtillerySpecialist
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetArtillerySpecialist
    jumpsuit: ClothingUniformJumpsuitSuppliesCrewman
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityFilled
    shoes: ClothingShoesBootsJack
