- type: job
  id: SuppliesCrewman
  name: job-name-suppliescrewman
  description: job-description-suppliescrewman
  playTimeTracker: JobSuppliesCrewman
  setPreference: true
  supervisors: job-supervisors-sq
  requirements:
  - !type:DepartmentTimeRequirement
    department: Supply
    time: 54000 # 15 hours
  displayWeight: 60
  startingGear: SuppliesCrewmanGear
  icon: "JobIconSuppliesCrewman"
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: SuppliesCrewmanGear
  equipment:
    id: CargoPDA
    head: ClothingHeadHatSuppliesCrewman
    ears: ClothingHeadsetSupplies
    jumpsuit: ClothingUniformJumpsuitSuppliesCrewman
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityFilled
    shoes: ClothingShoesBootsJack
