- type: job
  id: SuppliesQuartermaster
  name: job-name-suppliesquartermaster
  description: job-description-suppliesquartermaster
  playTimeTracker: JobSuppliesQuartermaster
  setPreference: true
  supervisors: job-supervisors-to
  requireAdminNotify: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Supply
      time: 54000 # 15 hours
  displayWeight: 100
  startingGear: SuppliesQuartermasterGear
  icon: "JobIconSuppliesQuartermaster"
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: SuppliesQuartermasterGear
  equipment:
    id: QuartermasterPDA
    head: ClothingHeadHatBeretSuppliesQuartermaster
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetSupplies
    jumpsuit: ClothingUniformJumpsuitSuppliesCrewman
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityFilled
    shoes: ClothingShoesBootsJack
