using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.FlagShip.Client.FTLDrive;

[GenerateTypedNameReferences]
public sealed partial class FTLDriveUI : FancyWindow
{
    public event Action? OnFTLDriveChargeButtonPressed;

    public FTLDriveUI()
    {
        RobustXamlLoader.Load(this);

        StartDriveButton.OnPressed += _ => OnFTLDriveChargeButtonPressed?.Invoke();
    }
}

