- type: job
  id: Custodian
  name: job-name-custodian
  description: job-description-custodian
  playTimeTracker: JobCustodian
  setPreference: true
  startingGear: CustodianGear
  icon: "JobIconCustodian"
  supervisors: job-supervisors-oo
  displayWeight: 100
  canBeAntag: true
  accessGroups:
  - Command
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: CustodianGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
