- type: job
  id: FlagResearchAssistant
  name: job-name-flag-research-assistant
  description: job-description-flag-research-assistant
  playTimeTracker: JobFlagResearchAssistant
  setPreference: true
  startingGear: FlagResearchAssistantGear
  icon: "JobIconFlagResearchAssistant"
  supervisors: job-supervisors-ss
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagScience
      time: 54000 # 15 hours
  displayWeight: 40
  accessGroups:
  - Research

- type: startingGear
  id: FlagResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
