- type: job
  id: FlagRoboticist
  name: job-name-flag-roboticist
  description: job-description-flag-roboticist
  playTimeTracker: JobFlagRoboticist
  setPreference: true
  startingGear: FlagRoboticistGear
  icon: "JobIconFlagRoboticist"
  supervisors: job-supervisors-ss
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagScience
      time: 54000 # 15 hours
  displayWeight: 60
  accessGroups:
  - Research

- type: startingGear
  id: FlagRoboticistGear
  equipment:
    shoes: ClothingShoesBootsJack
    id: HoSPDA
    ears: ClothingHeadsetCommandingOfficer
    belt: ClothingBeltSecurity
    uniform: ClothingUniformJumpsuitSec
