- type: job
  id: FlagScientist
  name: job-name-flag-scientist
  description: job-description-flag-scientist
  playTimeTracker: JobFlagScientist
  setPreference: true
  startingGear: FlagScientistGear
  icon: "JobIconFlagScientist"
  supervisors: job-supervisors-ss
  requirements:
    - !type:DepartmentTimeRequirement
      department: FlagScience
      time: 54000 # 15 hours
  displayWeight: 80
  accessGroups:
  - Research

- type: startingGear
  id: FlagScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: FlagScientistChameleonOutfit
  job: FlagScientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
